services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: legumexappsapi
    container_name: legumexappsapi
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: legumexappsapi-webservice
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: legumexappsapidb
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
